### ISSUE TITLE
import しても豆腐のままになる問題

### ISSUE THREAD

**Issue by masakiaota** [uehara1414/japanize-matplotlib#1]
素敵なものをありがとうございます。早速使ってみたのですが、importしても日本語が表示されません。二台のMacで試してみましたがどちらもだめでした。

試したときのnotebookはこちらになります。 念の為。
https://github.com/masakiaota/study/blob/master/my_cheatsheet/Seaborn.ipynb?short_path=1b80cf8

また、matplotlib等のバージョンは以下のようになっています。

jupyterlab                         0.35.3
japanize-matplotlib                1.0.4
matplotlib                         3.0.1

IPAフォントを自分でインストールいないと行けないのでしょうか？

**Comment by uehara1414** [comment]
ご利用・報告ありがとうございます！

リンク先のnotebookのコードをこちらの環境で再現してみたところ、同様に日本語表示部分が豆腐になりました。

原因を探ってみたところ、どうやら`sns.set()`の内部で`set_style(style, rc={"font.family": font})`
 というコードが実行されており、ここでseabornデフォルトのsans-serifが設定されてしまっているようです。こちらの環境では以下のように書き直したら問題なく日本語の表示ができるようになりました。
```diff
- sns.set()
+ sns.set(font="IPAexGothic")
```

もしくは、全ての事前設定の後に本モジュールをimportしてもらっても、日本語が表示されるはずです。

```diff
import matplotlib.pyplot as plt
- import japanize_matplotlib

import numpy as np
import pandas as pd

import seaborn as sns
sns.set()
+ import japanize_matplotlib

plt.plot([1, 2, 3, 4])
plt.xlabel('日本語を簡単に使える喜び')
plt.show()
```

いかがでしょう？
以上の修正でそちらの環境下で表示できればissueを閉じさせていただきます。

**Comment by masakiaota** [comment]
できました👏

seabornはfontまで自動で設定してしまうのですね。問題はなくなったのでissueはこちらで閉じておきます。
ありがとうございました。
