### ISSUE TITLE
conda 経由でインストールできるようにする

### ISSUE THREAD

**Issue by uehara1414** [uehara1414/japanize-matplotlib#18]
欲しい人いたらコメントかリアクションください

**Comment by KawabataLemon** [comment]
こんにちは。M1 Macで普段開発を行っているものです。M1 Mac下では、pyenvも動かず、パッケージとしてarm64環境が整っているのはcondaしかないためcondaから追加できるようになるのであれば大変助かります。ぜひご検討くだされば嬉しいです。

**Comment by uehara1414** [comment]
@J-taniguchi @KawabataLemon @taku-buntu @spring-haru @w-kote
```conda install -c uehara1414 japanize-matplotlib```

以上のコマンドで conda 経由でのインストールができるようになったはずです。
conda に詳しくないため正しく設定できているか確証が持てないので、動作確認などご協力お願いしたいです。
お手元の環境で試していただいて、インストール・動作に問題がなければ報告していただけると助かります。

**Comment by spring-haru** [comment]
インストールできますし，`matplotlib`で日本語が表示されます。ありがとうございます。

**Comment by uehara1414** [comment]
README.md にインストール方法記載しました。
動作確認ありがとうございました。
