### ISSUE TITLE
japanize-matplotlib経由でmatplotlibを呼び出せるようにする

### ISSUE THREAD

**Issue by massongit** [uehara1414/japanize-matplotlib#2]
以下のようなイメージで、japanize-matplotlib経由でmatplotlibを呼び出せるようにすると、japanize-matplotlibのimport文がフォーマッターに消されずに済むかと思います。

```py
from japanize_matplotlib import pyplot as plt

plt.plot([1, 2, 3, 4])
plt.xlabel('簡単なグラフ')
plt.show()
```

**Comment by uehara1414** [comment]
@massongit 
なるほどフォーマッターについては考えてませんでした。提案ありがとうございます。この実装だとimportのみの時から必要な行数を変えずにフォーマッターに消されないようにできますね！

しかしこのモジュールの役割は超単純に `matplotlib` を日本語化できることを目的にしているので、その点から考えて `matplotlib` を呼び出す実装は初見で「うん？」となるユーザーが多くなると思うので避けたいです。

単純に以下のように使えるようにするのはどうでしょう？冗長に感じますか？

```python
import japanize_matplotlib

japanize_matplotlib.japanize()  # import したときの処理をもう一度呼び出すだけ

```

**Comment by massongit** [comment]
提案いただいた書き方であればフォーマッターに消されることもないですし、良いと思います。
